ktor:
    apiKeys:
        githubSearchApiKey: $GITHUB_SEARCH_API_KEY
    application:
        modules:
            - io.github.aeckar.controller.ApplicationKt.module
    deployment:
        port: 8080
